[package]
name = "zap-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
pulldown-cmark = "0.13.0"
walkdir = "2.5.0"
